---
- name: Ensure homebrew is installed.
  git:
    repo: git://github.com/Homebrew/homebrew.git
    version: master
    dest: "{{ homebrew_install_path }}"
    update: no
    accept_hostkey: yes
  sudo: yes

- name: Ensure proper permissions on homebrew and bin directories.
  file:
    path: "{{ item }}"
    group: admin
    mode: 0775
  with_items:
    - "{{ homebrew_install_path }}"
    - "/usr/local"
  sudo: yes

- name: Check if homebrew binary is already in place.
  stat: path=/usr/local/bin/brew
  register: homebrew_binary

- name: Symlink brew to /usr/local/bin/brew.
  file:
    src: "{{ homebrew_install_path }}/bin/brew"
    dest: /usr/local/bin/brew
    state: link
  when: homebrew_binary.stat.exists == false
  sudo: yes

- include: tap.yml
- include: brew.yml
- include: cask.yml
  when: "'caskroom/cask' in homebrew_taps"
