---
- name: Get list of tapped homebrew taps.
  command: brew tap
  register: homebrew_tap_list
  always_run: yes
  changed_when: false

- name: Tap configured homebrew taps.
  command: "brew tap {{ item }}"
  with_items: homebrew_taps
  when: "'{{ item }}' not in homebrew_tap_list.stdout"
